### ISSUE TITLE
gateway/assets folder missing

### ISSUE THREAD

**Issue by Cmc7187** [binbat/live777#109]
gateway/assets folder is missing,can't build in release mode.
![img_v3_02a1_2a7be781-d584-4a17-a091-5075d7dc550g](https://github.com/binbat/live777/assets/73416531/103d0c02-7ea3-44f2-94e3-1d3b2e2de505)

**Comment by a-wing** [comment]
You need build frontend WebUI

```bash
bun install
bun run build
```

https://github.com/binbat/live777/blob/c01c1498552c31027ed2ecbac395c9b0e36af3ed/.github/workflows/rust.yml#L17-L23

**Comment by a-wing** [comment]
Added developer documentation: ef580af7c95b88598f3799b2eca87b9901d0e630
