### ISSUE TITLE
TypeError: this.trickle is not a function

### ISSUE THREAD

**Issue by a-wing** [binbat/live777#126]
<img width="760" alt="Screenshot 2024-05-10 at 21 21 52" src="https://github.com/binbat/live777/assets/18189138/c564590c-d4de-4e74-9a81-2f8beff7dd2f">

**Comment by a-wing** [comment]
@rocka now, We deploy a verge device. this device network is very complex.

I set turn server in iceserver, but The connect can't connected

Maybe is there have some problem

**Comment by a-wing** [comment]
I use [webrtc-rs#rtp-to-webrtc](https://github.com/webrtc-rs/webrtc/tree/master/examples/examples/rtp-to-webrtc) test this network.

When I set turn server in `rtp-to-webrtc` and Browser, This WevRTC P2P network is connected

**Comment by rocka** [comment]
> I set turn server in iceserver, but The connect can't connected

I've implemented the feature for the player page to use ice servers in URL params: #129 

As for the `TypeError`, it's not really relevant, the original whep.js does not have a `trickle()` function, but it's called in `setTimeout()` for some reason:

https://github.com/medooze/whip-whep-js/blob/13e211ad104f0ecb54465af971a49855d7788dc5/whep.js#L243-L245

I've removed it in our forked version, and it seems to work fine

https://github.com/binbat/whip-whep-js/commit/669e0878638f88bc15f05c76c2926c18ae43f050

**Comment by a-wing** [comment]
https://github.com/medooze/whip-whep-js/issues/26
