### ISSUE TITLE
how to test this project with the broswer?

### ISSUE THREAD

**Issue by snow2flying** [binbat/live777#14]
I got the server run with: cargo  run  --release
and client with:  gst-launch-1.0 videotestsrc ! videoconvert ! vp9enc ! rtpvp9pay ! whipsink whip-endpoint="http://localhost:3000/whip/777"
Both the server and client work pretty well. But when I open the browser I do not know what should I fill in the blank form in the following picture:
![image](https://github.com/binbat/live777/assets/48216860/a76f11a5-5f60-48db-bc9f-e3e6f7183f7f)

**Comment by a-wing** [comment]
Fill id: `777` after, click `WebRTC Start WHEP`

The API is `/whip/:id` and `/whep/:id`, input form need `:id`

**Comment by snow2flying** [comment]
Thanks, it works well.
Is there any plan for desktop native clients?

**Comment by a-wing** [comment]
>  Is there any plan for desktop native clients?

No, But maybe in the future, we will make some cli tools: `rtp-to-whip` and `whep-to-rtp`

In the future, Your can use:

```bash
ffmpeg -> rtp-to-whip -> live777 -> whep-to-rtp -> ffplay
```

>  or is it possible I can test it with gstreamer ?

Yes, Your can gstreamer test. But, need gstreamer plugin: `webrtchttp` on [gst-plugins-rs](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs)

**Comment by snow2flying** [comment]
> Yes, Your can gstreamer test. But, need gstreamer plugin: `webrtchttp` on [gst-plugins-rs](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs)

I do have gst-plugins-rs on my laptop.

This is my producer:
gst-launch-1.0 videotestsrc ! videoconvert ! x264enc ! rtph264pay ! whipsink whip-endpoint="http://localhost:3000/whip/777"

This is my consumer:
gst-launch-1.0 -v whepsrc whep-endpoint="http://localhost:3000/whep/777"     video-caps = "application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, payload=(int)33"     audio-caps = "application/x-rtp, media=(string)audio, encoding-name=(string)AAC, payload=(int)96" !     rtpmp2tdepay ! decodebin name=d     d. ! queue ! autovideosink sync=false     d. ! queue ! audioconvert ! autoaudiosink sync=false

This consumer works but it can not play the video or audio.
Do you have your own gstreamer command that works? if you have can you share it with me? 
Thanks

**Comment by a-wing** [comment]
I try use `whepsrc` plugin on `gst-plugins-rs`

But, This plugin isn't working. I don't recv any messages

I think this is a problem at [gst-plugins-rs#414](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/issues/414)

**Comment by snow2flying** [comment]
Thanks for your update.
If you get it work later, please update it here.
Thanks for you guys' hard work. This project is really awesome.

**Comment by a-wing** [comment]
Hey, We already add cli tools [rtp2whip](https://github.com/binbat/live777#rtp2whip) and [whep2rtp](https://github.com/binbat/live777#whep2rtp)

Welcome to try use canary version

**Comment by snow2flying** [comment]
any update about whep with gstreamer?

**Comment by a-wing** [comment]
Yes, I test this example, It's work

https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/issues/414#note_2091819

I  rename `rtp2whip` and `whep2rtp` #21 
- `rtp2whip` => `whipinto`
- `whep2rtp` => `whepfrom`

Also update readme 87972c4f975c73988ca92fd470bdeebb752759ab
