### ISSUE TITLE
whip / whep client close should delete resource

### ISSUE THREAD

**Issue by a-wing** [binbat/live777#16]
The client receive `Crtl+C` should delete the resource

https://github.com/binbat/live777/blob/425d72ea79a9a67e5960574b0657fca91aed732e/src/main.rs#L62

**Comment by hongcha98** [comment]
rtp2whip: https://github.com/binbat/live777/commit/23e00afba2d197201ea92cb423f58babc157e857
whep2rtp: https://github.com/binbat/live777/commit/d316757579e6fc0617458194b82879efc47e44aa

**Comment by a-wing** [comment]
Great
