### ISSUE TITLE
Add Authentication `auth-token`

### ISSUE THREAD

**Issue by a-wing** [binbat/live777#18]
RFC: https://datatracker.ietf.org/doc/html/draft-ietf-wish-whip#name-authentication-and-authoriz

For example GStreamer:

https://gstreamer.freedesktop.org/documentation/webrtchttp/whipsink.html#whipsink:auth-token

**Comment by hongcha98** [comment]
https://github.com/binbat/live777/commit/7a979189881480031cbbcf9d433af380e088c304

**Comment by a-wing** [comment]
I think `rtp2whip` and `whep2rtp` need this flag

**Comment by hongcha98** [comment]
rtp2whip: https://github.com/binbat/live777/commit/3a5ab0bb0724f63eb9167261af213615803b3fe6
whep2rtp: https://github.com/binbat/live777/commit/29f889da35cbd3d4452881873dddb74449eec92d

**Comment by hongcha98** [comment]
server: https://github.com/binbat/live777/commit/f261c5ed1b0938437e41f18cf37e24086fc9feab
