### ISSUE TITLE
Rename `rtp2whip` and `whep2rtp` ?

### ISSUE THREAD

**Issue by a-wing** [binbat/live777#21]
Maybe need a prefix. look like gstreamer: `whipsink` and `whepsrc`

- `rtp2whip` => `whipinto`
- `whep2rtp` => `whepfrom`

whip and whep common lib maybe rename

- `whip-whep` => `wish` (WebRTC Ingest Signaling over HTTPS)

Refence: https://datatracker.ietf.org/wg/wish/about/

**Comment by hongcha98** [comment]
Change whip-whep to whis-client,
Change rtp2whip to rtpwhis-into,
Change whep2rtp  to rtpwhis-form,
What do you recommend?

**Comment by a-wing** [comment]
Maybe, in the future?

Not just `rtp`, add `rtsp` is possibly

I think should save whip /whep, remove `rtp`
