### ISSUE TITLE
Errors occurred on the console after entering the URL to play the video

### ISSUE THREAD

**Issue by fastfeee** [binbat/live777#61]
Although the video will play normally，there was a PATCH  http://localhost:3000/whep/11 500 (Internal Server Error) and Uncaught (in promise)  Error: Request rejected with status 500 at WHEPClient.trickle (whep.js:337:32)

**Comment by a-wing** [comment]
Live777 Add must need If-Match header

Now, We're already fix this problem 6a2950fbadbcdb18dbde52d8d2ff8f2c5b00c832
